#ifndef __CODEX_TGMATH_H
#define __CODEX_TGMATH_H

#include <complex.h>
#include <math.h>

#define acos(x) _Generic((x), float: acosf, long double: acosl, float _Complex: cacosf, double _Complex: cacos, long double _Complex: cacosl, default: acos)(x)
#define asin(x) _Generic((x), float: asinf, long double: asinl, float _Complex: casinf, double _Complex: casin, long double _Complex: casinl, default: asin)(x)
#define atan(x) _Generic((x), float: atanf, long double: atanl, float _Complex: catanf, double _Complex: catan, long double _Complex: catanl, default: atan)(x)
#define acosh(x) _Generic((x), float: acoshf, long double: acoshl, float _Complex: cacoshf, double _Complex: cacosh, long double _Complex: cacoshl, default: acosh)(x)
#define asinh(x) _Generic((x), float: asinhf, long double: asinhl, float _Complex: casinhf, double _Complex: casinh, long double _Complex: casinhl, default: asinh)(x)
#define atanh(x) _Generic((x), float: atanhf, long double: atanhl, float _Complex: catanhf, double _Complex: catanh, long double _Complex: catanhl, default: atanh)(x)
#define cos(x) _Generic((x), float: cosf, long double: cosl, float _Complex: ccosf, double _Complex: ccos, long double _Complex: ccosl, default: cos)(x)
#define sin(x) _Generic((x), float: sinf, long double: sinl, float _Complex: csinf, double _Complex: csin, long double _Complex: csinl, default: sin)(x)
#define tan(x) _Generic((x), float: tanf, long double: tanl, float _Complex: ctanf, double _Complex: ctan, long double _Complex: ctanl, default: tan)(x)
#define cosh(x) _Generic((x), float: coshf, long double: coshl, float _Complex: ccoshf, double _Complex: ccosh, long double _Complex: ccoshl, default: cosh)(x)
#define sinh(x) _Generic((x), float: sinhf, long double: sinhl, float _Complex: csinhf, double _Complex: csinh, long double _Complex: csinhl, default: sinh)(x)
#define tanh(x) _Generic((x), float: tanhf, long double: tanhl, float _Complex: ctanhf, double _Complex: ctanh, long double _Complex: ctanhl, default: tanh)(x)
#define exp(x) _Generic((x), float: expf, long double: expl, float _Complex: cexpf, double _Complex: cexp, long double _Complex: cexpl, default: exp)(x)
#define log(x) _Generic((x), float: logf, long double: logl, float _Complex: clogf, double _Complex: clog, long double _Complex: clogl, default: log)(x)
#define pow(x, y) _Generic(((x) + (y)), float: powf, long double: powl, float _Complex: cpowf, double _Complex: cpow, long double _Complex: cpowl, default: pow)(x, y)
#define sqrt(x) _Generic((x), float: sqrtf, long double: sqrtl, float _Complex: csqrtf, double _Complex: csqrt, long double _Complex: csqrtl, default: sqrt)(x)

#define fabs(x) _Generic((x), float: fabsf, long double: fabsl, default: fabs)(x)
#define atan2(x, y) _Generic(((x) + (y)), float: atan2f, long double: atan2l, default: atan2)(x, y)
#define cbrt(x) _Generic((x), float: cbrtf, long double: cbrtl, default: cbrt)(x)
#define ceil(x) _Generic((x), float: ceilf, long double: ceill, default: ceil)(x)
#define copysign(x, y) _Generic(((x) + (y)), float: copysignf, long double: copysignl, default: copysign)(x, y)
#define erf(x) _Generic((x), float: erff, long double: erfl, default: erf)(x)
#define erfc(x) _Generic((x), float: erfcf, long double: erfcl, default: erfc)(x)
#define exp2(x) _Generic((x), float: exp2f, long double: exp2l, default: exp2)(x)
#define expm1(x) _Generic((x), float: expm1f, long double: expm1l, default: expm1)(x)
#define fdim(x, y) _Generic(((x) + (y)), float: fdimf, long double: fdiml, default: fdim)(x, y)
#define floor(x) _Generic((x), float: floorf, long double: floorl, default: floor)(x)
#define fma(x, y, z) _Generic(((x) + (y) + (z)), float: fmaf, long double: fmal, default: fma)(x, y, z)
#define fmax(x, y) _Generic(((x) + (y)), float: fmaxf, long double: fmaxl, default: fmax)(x, y)
#define fmin(x, y) _Generic(((x) + (y)), float: fminf, long double: fminl, default: fmin)(x, y)
#define fmod(x, y) _Generic(((x) + (y)), float: fmodf, long double: fmodl, default: fmod)(x, y)
#define frexp(x, y) _Generic((x), float: frexpf, long double: frexpl, default: frexp)(x, y)
#define hypot(x, y) _Generic(((x) + (y)), float: hypotf, long double: hypotl, default: hypot)(x, y)
#define ilogb(x) _Generic((x), float: ilogbf, long double: ilogbl, default: ilogb)(x)
#define ldexp(x, y) _Generic((x), float: ldexpf, long double: ldexpl, default: ldexp)(x, y)
#define lgamma(x) _Generic((x), float: lgammaf, long double: lgammal, default: lgamma)(x)
#define llrint(x) _Generic((x), float: llrintf, long double: llrintl, default: llrint)(x)
#define llround(x) _Generic((x), float: llroundf, long double: llroundl, default: llround)(x)
#define log10(x) _Generic((x), float: log10f, long double: log10l, default: log10)(x)
#define log1p(x) _Generic((x), float: log1pf, long double: log1pl, default: log1p)(x)
#define log2(x) _Generic((x), float: log2f, long double: log2l, default: log2)(x)
#define logb(x) _Generic((x), float: logbf, long double: logbl, default: logb)(x)
#define lrint(x) _Generic((x), float: lrintf, long double: lrintl, default: lrint)(x)
#define lround(x) _Generic((x), float: lroundf, long double: lroundl, default: lround)(x)
#define nearbyint(x) _Generic((x), float: nearbyintf, long double: nearbyintl, default: nearbyint)(x)
#define nextafter(x, y) _Generic(((x) + (y)), float: nextafterf, long double: nextafterl, default: nextafter)(x, y)
#define nexttoward(x, y) _Generic((x), float: nexttowardf, long double: nexttowardl, default: nexttoward)(x, y)
#define remainder(x, y) _Generic(((x) + (y)), float: remainderf, long double: remainderl, default: remainder)(x, y)
#define remquo(x, y, z) _Generic(((x) + (y)), float: remquof, long double: remquol, default: remquo)(x, y, z)
#define rint(x) _Generic((x), float: rintf, long double: rintl, default: rint)(x)
#define round(x) _Generic((x), float: roundf, long double: roundl, default: round)(x)
#define scalbln(x, y) _Generic((x), float: scalblnf, long double: scalblnl, default: scalbln)(x, y)
#define scalbn(x, y) _Generic((x), float: scalbnf, long double: scalbnl, default: scalbn)(x, y)
#define tgamma(x) _Generic((x), float: tgammaf, long double: tgammal, default: tgamma)(x)
#define trunc(x) _Generic((x), float: truncf, long double: truncl, default: trunc)(x)

#define cabs(x) _Generic((x), float: cabsf, long double: cabsl, float _Complex: cabsf, double _Complex: cabs, long double _Complex: cabsl, default: cabs)(x)
#define carg(x) _Generic((x), float: cargf, long double: cargl, float _Complex: cargf, double _Complex: carg, long double _Complex: cargl, default: carg)(x)
#define cimag(x) _Generic((x), float: cimagf, long double: cimagl, float _Complex: cimagf, double _Complex: cimag, long double _Complex: cimagl, default: cimag)(x)
#define conj(x) _Generic((x), float: conjf, long double: conjl, float _Complex: conjf, double _Complex: conj, long double _Complex: conjl, default: conj)(x)
#define cproj(x) _Generic((x), float: cprojf, long double: cprojl, float _Complex: cprojf, double _Complex: cproj, long double _Complex: cprojl, default: cproj)(x)
#define creal(x) _Generic((x), float: crealf, long double: creall, float _Complex: crealf, double _Complex: creal, long double _Complex: creall, default: creal)(x)

#endif
